name: DangerJS comment

on:
  workflow_run:
    workflows: ["DangerJS"]
    types:
      - completed

jobs:
  danger-comment:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "output.json"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/output.json.zip', Buffer.from(download.data));
      - run: unzip output.json.zip
      - name: Extract PR number
        id: pr-number
        run: |
          pr_number=$(jq --raw-output ".metadata.pr" output.json)
          echo "::set-output name=pr-id::${pr_number}"

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ steps.pr-number.outputs.pr-id }}
          comment-author: 'github-actions[bot]'
          body-includes: Textual map diff
      - name: Create or update comment
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const outputJsonText = fs.readFileSync('output.json', 'utf8');
            const outputJson = JSON.parse(outputJsonText);
            let commentBody = outputJsonText;
            const commentId = "${{ steps.fc.outputs.comment-id }}";
            if(commentId){
              github.rest.issues.updateComment({
                comment_id: commentId,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody
            })
            }

      # - build the output comment body
      # - find the previous comment
      # - post a new comment
      # think about using a git submodule to centrally manage scripts like above
      # see https://securitylab.github.com/research/github-actions-preventing-pwn-requests/