name: DangerJS

on: pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2.4.1
      with:
        node-version: "12.x"
    - name: Install yarn dependencies
      run: |
        yarn install --frozen-lockfile
        yarn danger ci -d danger/dangerfile.ts --outputJSON
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}