name: DangerJS

on: pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: get base branch as well
      run: |
        git fetch --depth=0 origin +refs/heads/${{github.base_ref}}:refs/remotes/origin/${{github.base_ref}}
    - name: Use Node.js
      uses: actions/setup-node@v2.4.1
      with:
        node-version: "12.x"
    - name: Install yarn dependencies
      run: |
        yarn install --frozen-lockfile
        yarn danger local -d danger/dangerfile.ts --outputJSON -b ${{ github.event.pull_request.base.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}